version: '2'
volumes:
  database_date:
    driver: local
    
services:
  nginx:
    image: nginx:1.15.1-alpine
    ports:
      - 8081:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./php
    expose:
      - 9000
    volumes:
      - .:/var/www/html


  mysql:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 4306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workshop
      MYSQL_USER: ma
      MYSQL_PASSWORD: password
